### ISSUE TITLE
The dist code[cjs.js] seems has mistake.

### ISSUE THREAD

**Issue by FPG-Alan** [facebook/facebook-nodejs-business-sdk#54] opened 2018-06-22 06:59 UTC
I am  trying use this SDK upload video to my AdAccount: 
```
let api = adsSdk.FacebookAdsApi.init(<token>)
api.setDebug(true)
let AdVideo = adsSdk.AdVideo
let advideo = new AdVideo(null, {[AdVideo.Fields.filepath]: "/path/to/video.mp4"}, "<ad account id>")
advideo.create().then(res=>{
    console.log(res)
})
```

And encountered an error says "_this8 is undefined".

The error trigged in `dist/cjs.js/VideoUploadTransferRequestManager.sendRequest`:
```
'use strict';
value: function sendRequest(context) {
    function _recursive() {
         var _this8 = this;
         if (_this8._startOffset !== _this8._endOffset) {
             ....
         }
    }
    ...
    ...
    return Promise.resolve().then(function () {
        ...
        ...
        return _recursive();
    }
}
```
As the announce 'use strict', `this` is `undefined` in `function _recursive`

And this function in source code is a `while` loop: 
```
async sendRequest (context: VideoUploadRequestContext): Object {
    ...
    this._startOffset = context.startOffset;
    this._endOffset = context.endOffset;
    ...
    while (this._startOffset !== this._endOffset) {
        ...
    }
    ...
}
``` 
I'm not familiar with flow, just want to figure out is this a compile error?

**Comment by vicdus** [comment] 2018-06-22 18:23
Hi,

I cannot reproduce this error. My step:

```
mkdir repoduce
cd reproduce
npm init
npm install --save facebook-nodejs-business-sdk
```
and my code
```
const adsSdk = require('facebook-nodejs-business-sdk');
const accessToken = 'mytoken';
const api = adsSdk.FacebookAdsApi.init(accessToken);

api.setDebug(true)
let AdVideo = adsSdk.AdVideo
let advideo = new AdVideo(null, {[AdVideo.Fields.filepath]: "sample.mp4"}, "act_<myadaccount>")
advideo.create().then(res=>{
	console.log(res)
})
```

Got 200 status code (although with unhandled promise reject warnings)

**Comment by FPG-Alan** [comment] 2018-06-25 01:57
@vicdus thanks for your response, actually, I got this log use either your code or mine: 
```
200 POST https://graph-video.facebook.com/v3.0/act_adaccount/advideos?access_token=token {"file_size":799801,"upload_phase":"start"}
Response: "{\"video_id\":\"videoid\",\"start_offset\":\"0\",\"end_offset\":\"799801\",\"upload_session_id\":\"upload_session_id\"}"

(node:2516) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_startOffset' of undefined
```

I think the 200 status code indicate a "Chunked Upload" begin, 
and the unhandled promise reject warnings shows an error which i posted before, 
the promise reject interrupted the upload.

**Comment by vicdus** [comment] 2018-06-26 22:12
Hi, 
We've already located the problem. Seems that is caused by gulp and we are working on fix it.

We will fix this ASAP in next release, but a quick workaround will be replace the ```./dist/cjs.js``` line 1983 from
```var _this8 = this;``` to ```var _this8 = _this7;```

and the new method will be like 
```
    value: function sendRequest(context) {
      function _recursive() {
        var _this8 = _this7;  // <- this line changed
```

**Comment by FPG-Alan** [comment] 2018-06-27 01:48
@vicdus the workaround works for me, thanks for your work!

**Comment by michaelwclark** [comment] 2019-05-08 16:24
@FPG-Alan  can you close this if it's resolved?

**Closed** 2019-05-13 06:40 UTC

**Comment by briank621** [comment] 2019-05-21 17:56
I don't believe that the fix has been pushed to master. Is there any update on this or perhaps more details on how to fix the gulpfile so a PR can be made?

**Comment by mvhirsch** [comment] 2019-09-08 10:00
@vicdus I'm still running into this issue (SDK: `v4.0.3`). 
Are there any news on fixing this?
