### ISSUE TITLE
Can't get "Campaign" details from Insights report

### ISSUE THREAD

**Issue by Axel186** [facebook/facebook-nodejs-business-sdk#95] opened 2019-01-03 17:44 UTC
I am trying to use the `getInsights` method and everything works well.
But now I have discovered that `campaign_id` and `campaign_name`, fields that should be available are always appears as `undefined` in my reports.

Here is an example of code that I run:
```
const params = {level:"account", filtering:[], breakdowns:[], time_range:{since:"2014-08-01",until:"2014-12-22"}};
const fields = ["impressions", "campaign_id", "campaign_name"];
new AdAccount('MY_ACCOUNT_ID_HERE').getInsights(fields, params)
    .then(result => {
        // result[0].impressions ---> "71035"
        // result[0].campaign_id ---> undefined
        // result[0].campaign_name ---> undefined
    })
```

The case is related to `campaign_id`, `campaign_name`, `adset_id` and `adset_name`...
Things like `account_id` and `account_name` work properly.

I wounder, what's wrong in my request?
Looking for help.

**Comment by jingping2015** [comment] 2019-01-03 18:34
Hi, Thanks for reporting this issue.
Can you please try with Graph API call to check if that works? If API also return empty/undefined value, please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

**Comment by jingping2015** [comment] 2019-01-09 00:37
I will close this now, feel free to re-open it if SDK have different result than Graph API.

**Closed by jingping2015** 2019-01-09 00:37 UTC

**Comment by MarkRatFelt** [comment] 2022-03-29 17:09
This is pretty old, but just in case someone has the same problem. 

The problem is that you should use 

```JS
const AdsInsights = bizSdk.AdsInsights
params = {
    'level': AdsInsights.Level.campaign
};
```
And then it should work.
